/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author Patin
 */
public class VistaPersonaje extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPersonaje.class.getName());

    /**
     * Creates new form VistaPersonaje
     */
    public VistaPersonaje() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblGestionPersonaje = new javax.swing.JLabel();
        jTabbedPa = new javax.swing.JTabbedPane();
        jPanel_agregrarPersonaje = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblClase = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblExperiencia = new javax.swing.JLabel();
        lblSalud = new javax.swing.JLabel();
        lblMana = new javax.swing.JLabel();
        lblFuerza = new javax.swing.JLabel();
        lblAgilidad = new javax.swing.JLabel();
        lblInteligencia = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtClase = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        txtExperiencia = new javax.swing.JTextField();
        txtSalud = new javax.swing.JTextField();
        txtMana = new javax.swing.JTextField();
        txtFuerza = new javax.swing.JTextField();
        txtAgilidad = new javax.swing.JTextField();
        txtInteligencia = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jPanel_borrarPersonaje = new javax.swing.JPanel();
        jPanel_editarPersonaje = new javax.swing.JPanel();
        jPanel_listarPersonaje = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 650));

        lblGestionPersonaje.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        lblGestionPersonaje.setText("Gestion Personajes");

        java.awt.GridBagLayout jPanel_agregrarPersonajeLayout = new java.awt.GridBagLayout();
        jPanel_agregrarPersonajeLayout.columnWidths = new int[] {0, 12, 0};
        jPanel_agregrarPersonajeLayout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel_agregrarPersonaje.setLayout(jPanel_agregrarPersonajeLayout);

        lblId.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel_agregrarPersonaje.add(lblId, gridBagConstraints);

        lblNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel_agregrarPersonaje.add(lblNombre, gridBagConstraints);

        lblClase.setText("Clase");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel_agregrarPersonaje.add(lblClase, gridBagConstraints);

        lblNivel.setText("Nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel_agregrarPersonaje.add(lblNivel, gridBagConstraints);

        lblExperiencia.setText("Experiencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel_agregrarPersonaje.add(lblExperiencia, gridBagConstraints);

        lblSalud.setText("Salud");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        jPanel_agregrarPersonaje.add(lblSalud, gridBagConstraints);

        lblMana.setText("Mana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        jPanel_agregrarPersonaje.add(lblMana, gridBagConstraints);

        lblFuerza.setText("Fuerza");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        jPanel_agregrarPersonaje.add(lblFuerza, gridBagConstraints);

        lblAgilidad.setText("Agilidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        jPanel_agregrarPersonaje.add(lblAgilidad, gridBagConstraints);

        lblInteligencia.setText("Inteligencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        jPanel_agregrarPersonaje.add(lblInteligencia, gridBagConstraints);

        txtId.setToolTipText("prepre");
        txtId.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_agregrarPersonaje.add(txtId, gridBagConstraints);

        txtNombre.setToolTipText("prepre");
        txtNombre.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_agregrarPersonaje.add(txtNombre, gridBagConstraints);

        txtClase.setToolTipText("prepre");
        txtClase.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_agregrarPersonaje.add(txtClase, gridBagConstraints);

        txtNivel.setToolTipText("prepre");
        txtNivel.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_agregrarPersonaje.add(txtNivel, gridBagConstraints);

        txtExperiencia.setToolTipText("prepre");
        txtExperiencia.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_agregrarPersonaje.add(txtExperiencia, gridBagConstraints);

        txtSalud.setToolTipText("prepre");
        txtSalud.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_agregrarPersonaje.add(txtSalud, gridBagConstraints);

        txtMana.setToolTipText("prepre");
        txtMana.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_agregrarPersonaje.add(txtMana, gridBagConstraints);

        txtFuerza.setToolTipText("prepre");
        txtFuerza.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_agregrarPersonaje.add(txtFuerza, gridBagConstraints);

        txtAgilidad.setToolTipText("prepre");
        txtAgilidad.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_agregrarPersonaje.add(txtAgilidad, gridBagConstraints);

        txtInteligencia.setToolTipText("prepre");
        txtInteligencia.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_agregrarPersonaje.add(txtInteligencia, gridBagConstraints);

        btnGuardar.setText("GUARDAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 3;
        jPanel_agregrarPersonaje.add(btnGuardar, gridBagConstraints);

        jTabbedPa.addTab("Agregar Personaje", jPanel_agregrarPersonaje);

        javax.swing.GroupLayout jPanel_borrarPersonajeLayout = new javax.swing.GroupLayout(jPanel_borrarPersonaje);
        jPanel_borrarPersonaje.setLayout(jPanel_borrarPersonajeLayout);
        jPanel_borrarPersonajeLayout.setHorizontalGroup(
            jPanel_borrarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        jPanel_borrarPersonajeLayout.setVerticalGroup(
            jPanel_borrarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        jTabbedPa.addTab("Borrar Personaje", jPanel_borrarPersonaje);

        javax.swing.GroupLayout jPanel_editarPersonajeLayout = new javax.swing.GroupLayout(jPanel_editarPersonaje);
        jPanel_editarPersonaje.setLayout(jPanel_editarPersonajeLayout);
        jPanel_editarPersonajeLayout.setHorizontalGroup(
            jPanel_editarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        jPanel_editarPersonajeLayout.setVerticalGroup(
            jPanel_editarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        jTabbedPa.addTab("Editar Personaje", jPanel_editarPersonaje);

        java.awt.GridBagLayout jPanel_listarPersonajeLayout = new java.awt.GridBagLayout();
        jPanel_listarPersonajeLayout.columnWidths = new int[] {0};
        jPanel_listarPersonajeLayout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0};
        jPanel_listarPersonaje.setLayout(jPanel_listarPersonajeLayout);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel_listarPersonaje.add(jScrollPane1, gridBagConstraints);

        jButton1.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel_listarPersonaje.add(jButton1, gridBagConstraints);

        jTabbedPa.addTab("Listar Personaje", jPanel_listarPersonaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPa)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lblGestionPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblGestionPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTabbedPa)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPersonaje().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel_agregrarPersonaje;
    private javax.swing.JPanel jPanel_borrarPersonaje;
    private javax.swing.JPanel jPanel_editarPersonaje;
    private javax.swing.JPanel jPanel_listarPersonaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPa;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAgilidad;
    private javax.swing.JLabel lblClase;
    private javax.swing.JLabel lblExperiencia;
    private javax.swing.JLabel lblFuerza;
    private javax.swing.JLabel lblGestionPersonaje;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInteligencia;
    private javax.swing.JLabel lblMana;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSalud;
    private javax.swing.JTextField txtAgilidad;
    private javax.swing.JTextField txtClase;
    private javax.swing.JTextField txtExperiencia;
    private javax.swing.JTextField txtFuerza;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtInteligencia;
    private javax.swing.JTextField txtMana;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalud;
    // End of variables declaration//GEN-END:variables
}
